Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Gitlab Orange 2: 
> Full results can be seen here: https://logs.onap.org/onap-integration/gating//116744-1/index.html
> ______________ Results ______________________
> 
> ************************************************************
> ************************************************************
> ************ Infrastructure-healthcheck Results ************
> ************************************************************
> ************************************************************
> --------> onap-k8s
>  * Nb Jobs: 27
>  * Nb Failed Jobs: 1
>  * List of Failed Jobs: [
>    - onap-dmaap-bc-dmaap-provisioning]
>  * Nb Deployments: 154
>  * Nb Failed Deployments: 1
>  * List of Failed Deployments: [
>    - onap-dmaap-bc]
>  * Nb StatefulSets: 29
>  * Nb Failed StatefulSets: 0
>  * Nb Persistent Volume Claims: 79
>  * Nb Failed Persistent Volume Claims: 0
> --------> onap-helm
>  * Nb Helms: 33
>  * Nb Failed Helms: 1
>  * List of Failed Helms: [
>    - onap-so]
> 
> ************************************************************
> ************************************************************
> ********************* Healthcheck Results ******************
> ************************************************************
> ************************************************************
> --------> robot  full healthcheck tests
> 2021-01-12 13:34:42,286 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Health-Check :: Test that ONAP components are available via basic API calls   
> ==============================================================================
> Basic A&AI Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced A&AI Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic AAF Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic AAF SMS Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic APPC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic CLI Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic CLAMP Health Check                                              | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Data Router Health Check                                  | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Message Router Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
> ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff146157710>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic External API NBI Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Microservice Bus Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-pike API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-starlingx API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-vio API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-k8s API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-Homing Health Check                                         | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-OSDF Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-CMSO Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic Policy Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Enhanced Policy New Healthcheck                                       | PASS |
> ------------------------------------------------------------------------------
> Basic Portal Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDC Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDC Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDNC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDNC Health Check                                            | FAIL |
> Test timeout 20 seconds exceeded.
> ------------------------------------------------------------------------------
> Basic SO Health Check                                                 | PASS |
> ------------------------------------------------------------------------------
> Basic UseCaseUI API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC gvnfmdriver API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic VFC nslcm API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnflcm API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfmgr API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfres API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC ztevnfmdriver API Health Check                              | PASS |
> ------------------------------------------------------------------------------
> Basic VID Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic VNFSDK Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-fcaps API Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic Modeling genericparser API Health Check                         | PASS |
> ------------------------------------------------------------------------------
> Enhanced CDS Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> 43 critical tests, 41 passed, 2 failed
> 43 tests total, 41 passed, 2 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/full/output.xml
> --------> healthdist (vFW onboarding and distribution)
> 2021-01-12 13:38:54,057 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Health-Check :: Test that ONAP components are available via basic API calls   
> ==============================================================================
> Health Distribution Test                                              | PASS |
> ------------------------------------------------------------------------------
> Health-Check :: Test that ONAP components are available via basic ... | PASS |
> 1 critical test, 1 passed, 0 failed
> 1 test total, 1 passed, 0 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/healthdist/output.xml
> --------> postinstall tests (dmaap and A&AI)
> 2021-01-12 13:32:58,544 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Post-Install-Tests :: Testing Installation                                    
> ==============================================================================
> Basic DMAAP Message Router ACL Update Test                            | PASS |
> ------------------------------------------------------------------------------
> Basic AAI Service Design Models Size Test                             | PASS |
> ------------------------------------------------------------------------------
> Post-Install-Tests :: Testing Installation                            | PASS |
> 2 critical tests, 2 passed, 0 failed
> 2 tests total, 2 passed, 0 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/postinstall/output.xml
> 
> 
> ************************************************************
> ************************************************************
> ********************** Smoke usecases **********************
> ************************************************************
> ************************************************************
> --------> End to End tests (onap-tests)
> basic_vm: FAIL (21:05)
> basic_network: FAIL (23:49)
> pnf-registrate: FAIL (09:48)
> hv-ves: PASS (00:46)
> 5gbulkpm: FAIL (12:07)
> 
> ************************************************************
> ************************************************************
> ********************** Security tests **********************
> Security tests not executed
> 
> ____________________________________________________________

on "tsandard" gating, issues during installation but robot pod is up https://logs.onap.org/onap-integration/gating//116744-1/infrastructure-healthcheck/k8s/kubernetes-status/pod-onap-robot-b755ffd44-4v47v.html
and this pod is not invovled directly in ONAP installation, it is used to launch some tests (not the ones from the CI)

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>